### ISSUE TITLE
Include operators with no `Combine` equivalent

### ISSUE THREAD

**Issue by stephencelis** [freak4pc/rxswift-to-combine-cheatsheet#3]
Would be nice to visualize all the operators RxSwift (and common extensions) provide that Combine decided _not_ to include thus far

**Comment by freak4pc** [comment]
Good idea - maybe I'll revise the list to have all Rx operators with any (if) parallels on the right side. I'll try to find some time for this soon :)

**Comment by freak4pc** [comment]
Mostly fixed in 0f6ab7c88e1254b29521183f6144885815f632be. Let me know if you have any other thoughts :)
