### ISSUE TITLE
Does not demonstrate Publishers.CombineLatest

### ISSUE THREAD

**Issue by brookshanes** [freak4pc/rxswift-to-combine-cheatsheet#30]
Unable to push to repo, so I'll put an issue here. To refactor from RxSwift's `combineLatest`, I'm thinking of using `Publishers.CombineLatest` static init.

**Comment by freak4pc** [comment]
Hey, we're already mentioning `combineLatest` itself from Combine - which is just a wrapper to Publishers.CombineLatest
